export const courses = [
  {
    periodo: 1,
    cursos: [
      {
        idCourse: 1,
        name: "MATEMÁTICAS DISCRETAS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 2,
        name: "FUNDAMENTOS DE FÍSICA",
        tipo: "OBLIGATORIA",
        creditos: 8.0,
        horasTeoricas: 4.0,
        horasPracticas: 0.0,
      },
      {
        idCourse: 3,
        name: "FÍSICA GENERAL EXPERIMENTAL",
        tipo: "OBLIGATORIA",
        creditos: 2.0,
        horasTeoricas: 0.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 4,
        name: "COMUNICACIÓN PROFESIONAL INTERDISCIPLINARIA",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 5,
        name: "FUNDAMENTOS DE ADMINISTRACIÓN",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 6,
        name: "RESPONSABILIDAD SOCIAL Y ÉTICA",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 7,
        name: "LÓGICA DE PROGRAMACIÓN",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
    ],
  },
  {
    periodo: 2,
    cursos: [
      {
        idCourse: 8,
        name: "CÁLCULO DIFERENCIAL E INTEGRAL",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 9,
        name: "PSICOLOGÍA EN EL TRABAJO",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 10,
        name: "METODOLOGÍA DE LA INVESTIGACIÓN",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 11,
        name: "SISTEMAS DIGITALES",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 12,
        name: "APLICACIÓN DE SISTEMAS DIGITALES",
        tipo: "OBLIGATORIA",
        creditos: 4.0,
        horasTeoricas: 1.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 13,
        name: "FUNDAMENTOS DE INGENIERÍA DE SOFTWARE",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 14,
        name: "ESTRUCTURA DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 15,
        name: "PROGRAMACIÓN DE BAJO NIVEL",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
    ],
  },
  {
    periodo: 3,
    cursos: [
      {
        idCourse: 16,
        name: "PROBABILIDAD",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 17,
        name: "ALGORITMOS COMPUTACIONALES",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 18,
        name: "INGENIERÍA DE REQUERIMIENTOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 19,
        name: "DISEÑO DE INTERFACES DE USUARIO",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 20,
        name: "ARQUITECTURA Y ORGANIZACIÓN DE LAS COMPUTADORAS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 21,
        name: "CONSTRUCCIÓN DE BASES DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 22,
        name: "PROGRAMACIÓN ORIENTADA A OBJETOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
    ],
  },
  {
    periodo: 4,
    cursos: [
      {
        idCourse: 23,
        name: "ESTADÍSTICA",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 24,
        name: "DISPOSITIVOS PROGRAMABLES",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 1.0,
        horasPracticas: 3.0,
      },
      {
        idCourse: 25,
        name: "INGENIERÍA DE DISEÑO",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 26,
        name: "ADMINISTRACIÓN DE BASES DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 27,
        name: "SEGURIDAD INFORMÁTICA",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 28,
        name: "SISTEMAS OPERATIVOS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 29,
        name: "ADQUISICIÓN DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
    ],
  },
  {
    periodo: 5,
    cursos:[
      {
        idCourse: 30,
        name: "ÁLGEBRA LINEAL",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 31,
        name: "ESCENARIOS VIRTUALES",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 32,
        name: "HACKEO ÉTICO",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 33,
        name: "SISTEMAS EMBEBIDOS",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 34,
        name: "MÉTODOS NUMÉRICOS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 35,
        name: "CONTABILIDAD FINAN. Y DE COSTOS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 36,
        name: "APLICACIÓN DE LA CIENCIA ECONÓMICA",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 37,
        name: "TEORÍA DE LA COMP. Y COMP.",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 38,
        name: "COMUNICACIÓN DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 39,
        name: "PROGRAMACIÓN WEB",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      }      
    ]
  },
  {
    periodo: 6,
    cursos:[
      {
        idCourse: 40,
        name: "AMBIENTES VIRTUALES INMERSIVOS",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 41,
        name: "INFO. EN AMBIENTES PRODUCTIVOS",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 42,
        name: "MOD. DETER. DE INV. DE OPERACIONES",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 43,
        name: "VIROLOGÍA Y CRIPTOGRAFÍA ",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 44,
        name: "INGENIERÍA ECONÓMICA",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 45,
        name: "PRESUPUESTO Y FINANZAS",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 46,
        name: "REDES Y CONECTIVIDAD",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 47,
        name: "FUND. DE INTELIGENCIA ARTIFICIAL",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 48,
        name: "INGENIERÍA DE PRUEBAS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 49,
        name: "PROGRAMACIÓN MÓVIL",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      }
    ]
  },
  {
    periodo: 7,
    cursos:[
      {
        idCourse: 50,
        name: "BIG DATA Y TOMA DE DECISIONES",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 51,
        name: "MONITOREO Y ADMIN. DE REDES",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 52,
        name: "REDES Y MODELOS DE SIMULACIÓN",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 53,
        name: "SIMULADORES VIRTUALES",
        tipo: "OPTATIVA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 54,
        name: "ADMINISTRACIÓN ESTRATÉGICA",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 55,
        name: "LEGISLACIÓN INFORMÁTICA",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 56,
        name: "FORM. Y EVAL. DE PROYECTOS",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 1.0,
        horasPracticas: 3.0,
      },
      {
        idCourse: 57,
        name: "INGENIERÍA DEL CONOCIMIENTO",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 58,
        name: "INTERNET DE LAS COSAS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 59,
        name: "SEGURIDAD EN REDES",
        tipo: "OBLIGATORIA",
        creditos: 7.0,
        horasTeoricas: 3.0,
        horasPracticas: 1.0,
      }
    ]
  },
  {
    periodo: 8,
    cursos:[
      {
        idCourse: 60,
        name: "HABILIDADES DIRECTIVAS",
        tipo: "OBLIGATORIA",
        creditos: 4.0,
        horasTeoricas: 1.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 61,
        name: "INFORMÁTICA EMPRESARIAL",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 2.0,
        horasPracticas: 1.0,
      },
      {
        idCourse: 62,
        name: "PROYECTO DE TITULACIÓN",
        tipo: "OBLIGATORIA",
        creditos: 3.0,
        horasTeoricas: 0.0,
        horasPracticas: 3.0,
      },
      {
        idCourse: 63,
        name: "GESTIÓN DE PROYECTOS",
        tipo: "OBLIGATORIA",
        creditos: 5.0,
        horasTeoricas: 1.0,
        horasPracticas: 3.0,
      },
      {
        idCourse: 64,
        name: "CALIDAD Y NORM. DE SOFTWARE",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 65,
        name: "ADMINISTRACIÓN DE TECNOLOGÍAS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 66,
        name: "FUNDAMENTOS DE ANALÍTICA DE DATOS",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      },
      {
        idCourse: 67,
        name: "COMPUTACIÓN EN LA NUBE",
        tipo: "OBLIGATORIA",
        creditos: 6.0,
        horasTeoricas: 2.0,
        horasPracticas: 2.0,
      }
    ]
  }
];

console.log(courses);