/**
 * @typedef {Object} Course
 * @property {int} idCourse - Identificador del curso
 * @property {int} periodo - Periodo en el que se cursa
 * @property {string} name - Nombre del material
 * @property {string} tipo - Tipo de material
 * @property {double} creditos - Creditos del material
 * @property {int} horasTeoricas - Horas de teoria por semana
 * @property {int} horasPracticas - Horas practicas por semana
 */

export const courses = [
  [
    {
      idCourse: 1,
      periodo: 1,
      name: "MATEMÁTICAS DISCRETAS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 2,
      periodo: 1,
      name: "FUNDAMENTOS DE FÍSICA",
      tipo: "OBLIGATORIA",
      creditos: 8.0,
      horasTeoricas: 4.0,
      horasPracticas: 0.0,
    },
    {
      idCourse: 3,
      periodo: 1,
      name: "FÍSICA GENERAL EXPERIMENTAL",
      tipo: "OBLIGATORIA",
      creditos: 2.0,
      horasTeoricas: 0.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 4,
      periodo: 1,
      name: "COMUNICACIÓN PROFESIONAL INTERDISCIPLINARIA",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 5,
      periodo: 1,
      name: "FUNDAMENTOS DE ADMINISTRACIÓN",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 6,
      periodo: 1,
      name: "RESPONSABILIDAD SOCIAL Y ÉTICA",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 7,
      periodo: 1,
      name: "LÓGICA DE PROGRAMACIÓN",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 8,
      periodo: 2,
      name: "CÁLCULO DIFERENCIAL E INTEGRAL",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 9,
      periodo: 2,
      name: "PSICOLOGÍA EN EL TRABAJO",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 10,
      periodo: 2,
      name: "METODOLOGÍA DE LA INVESTIGACIÓN",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 11,
      periodo: 2,
      name: "SISTEMAS DIGITALES",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 12,
      periodo: 2,
      name: "APLICACIÓN DE SISTEMAS DIGITALES",
      tipo: "OBLIGATORIA",
      creditos: 4.0,
      horasTeoricas: 1.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 13,
      periodo: 2,
      name: "FUNDAMENTOS DE INGENIERÍA DE SOFTWARE",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 14,
      periodo: 2,
      name: "ESTRUCTURA DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 15,
      periodo: 2,
      name: "PROGRAMACIÓN DE BAJO NIVEL",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 16,
      periodo: 3,
      name: "PROBABILIDAD",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 17,
      periodo: 3,
      name: "ALGORITMOS COMPUTACIONALES",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 18,
      periodo: 3,
      name: "INGENIERÍA DE REQUERIMIENTOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 19,
      periodo: 3,
      name: "DISEÑO DE INTERFACES DE USUARIO",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 20,
      periodo: 3,
      name: "ARQUITECTURA Y ORGANIZACIÓN DE LAS COMPUTADORAS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 21,
      periodo: 3,
      name: "CONSTRUCCIÓN DE BASES DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 22,
      periodo: 3,
      name: "PROGRAMACIÓN ORIENTADA A OBJETOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 23,
      periodo: 4,
      name: "ESTADÍSTICA",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 24,
      periodo: 4,
      name: "DISPOSITIVOS PROGRAMABLES",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 1.0,
      horasPracticas: 3.0,
    },
    {
      idCourse: 25,
      periodo: 4,
      name: "INGENIERÍA DE DISEÑO",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 26,
      periodo: 4,
      name: "ADMINISTRACIÓN DE BASES DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 27,
      periodo: 4,
      name: "SEGURIDAD INFORMÁTICA",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 28,
      periodo: 4,
      name: "SISTEMAS OPERATIVOS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 29,
      periodo: 4,
      name: "ADQUISICIÓN DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 30,
      periodo: 5,
      name: "ÁLGEBRA LINEAL",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 31,
      periodo: 5,
      name: "ESCENARIOS VIRTUALES (COMPUTACIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 32,
      periodo: 5,
      name: "HACKEO ÉTICO (INFORMÁTICA)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 33,
      periodo: 5,
      name: "SISTEMAS EMBEBIDOS (LABORATORIO DE ELECTRICIDAD Y CONTROL)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 34,
      periodo: 5,
      name: "MÉTODOS NUMÉRICOS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 35,
      periodo: 5,
      name: "CONTABILIDAD FINANCIERA Y DE COSTOS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 36,
      periodo: 5,
      name: "APLICACIÓN DE LA CIENCIA ECONÓMICA",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 37,
      periodo: 5,
      name: "TEORÍA DE LA COMPUTACIÓN Y COMPILADORES",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 38,
      periodo: 5,
      name: "COMUNICACIÓN DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 39,
      periodo: 5,
      name: "PROGRAMACIÓN WEB",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 40,
      periodo: 6,
      name: "AMBIENTES VIRTUALES INMERSIVOS (COMPUTACIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 41,
      periodo: 6,
      name: "INFORMÁTICA EN AMBIENTES PRODUCTIVOS (PRODUCCIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 42,
      periodo: 6,
      name: "MODELOS DETERMINÍSTICOS DE INVESTIGACIÓN DE OPERACIONES",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 43,
      periodo: 6,
      name: "VIROLOGÍA Y CRIPTOGRAFÍA (COMPUTACIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 44,
      periodo: 6,
      name: "INGENIERÍA ECONÓMICA",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 45,
      periodo: 6,
      name: "PRESUPUESTO Y FINANZAS",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 46,
      periodo: 6,
      name: "REDES Y CONECTIVIDAD",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 47,
      periodo: 6,
      name: "FUNDAMENTOS DE INTELIGENCIA ARTIFICIAL",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 48,
      periodo: 6,
      name: "INGENIERÍA DE PRUEBAS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 49,
      periodo: 6,
      name: "PROGRAMACIÓN MÓVIL",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
  [
    {
      idCourse: 50,
      periodo: 7,
      name: "BIG DATA Y TOMA DE DECISIONES (INFORMÁTICA)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 51,
      periodo: 7,
      name: "MONITOREO Y ADMINISTRACIÓN DE REDES (COMPUTACIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 52,
      periodo: 7,
      name: "REDES Y MODELOS DE SIMULACIÓN",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 53,
      periodo: 7,
      name: "SIMULADORES VIRTUALES (COMPUTACIÓN)",
      tipo: "OPTATIVA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 54,
      periodo: 7,
      name: "ADMINISTRACIÓN ESTRATÉGICA",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 55,
      periodo: 7,
      name: "LEGISLACIÓN INFORMÁTICA",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 56,
      periodo: 7,
      name: "FORMULACIÓN Y EVALUACIÓN DE PROYECTOS",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 1.0,
      horasPracticas: 3.0,
    },
    {
      idCourse: 57,
      periodo: 7,
      name: "INGENIERÍA DEL CONOCIMIENTO",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 58,
      periodo: 7,
      name: "INTERNET DE LAS COSAS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 59,
      periodo: 7,
      name: "SEGURIDAD EN REDES",
      tipo: "OBLIGATORIA",
      creditos: 7.0,
      horasTeoricas: 3.0,
      horasPracticas: 1.0,
    },
  ],
  [
    {
      idCourse: 60,
      periodo: 8,
      name: "HABILIDADES DIRECTIVAS",
      tipo: "OBLIGATORIA",
      creditos: 4.0,
      horasTeoricas: 1.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 61,
      periodo: 8,
      name: "INFORMÁTICA EMPRESARIAL",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 2.0,
      horasPracticas: 1.0,
    },
    {
      idCourse: 62,
      periodo: 8,
      name: "PROYECTO DE TITULACIÓN",
      tipo: "OBLIGATORIA",
      creditos: 3.0,
      horasTeoricas: 0.0,
      horasPracticas: 3.0,
    },
    {
      idCourse: 63,
      periodo: 8,
      name: "GESTIÓN DE PROYECTOS",
      tipo: "OBLIGATORIA",
      creditos: 5.0,
      horasTeoricas: 1.0,
      horasPracticas: 3.0,
    },
    {
      idCourse: 64,
      periodo: 8,
      name: "CALIDAD Y NORMALIZACIÓN DE SOFTWARE",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 65,
      periodo: 8,
      name: "ADMINISTRACIÓN DE TECNOLOGÍAS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 66,
      periodo: 8,
      name: "FUNDAMENTOS DE ANALÍTICA DE DATOS",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
    {
      idCourse: 67,
      periodo: 8,
      name: "COMPUTACIÓN EN LA NUBE",
      tipo: "OBLIGATORIA",
      creditos: 6.0,
      horasTeoricas: 2.0,
      horasPracticas: 2.0,
    },
  ],
];
