export const schedules = [
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 147,
      shift: "M",
      group_idgroup: 45,
      course_idCourse: 24,
      teacher_idTeacher: 109,
      building: "LE",
      classroom: 1,
      monday: ["08:30", "10:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: [""],
      group: "3NM42",
      profesor: "ARMANDO TORRES CORONEL",
      asignatura: "DISPOSITIVOS PROGRAMABLES",
    },
    {
      idschedule: 185,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 26,
      teacher_idTeacher: 141,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["12:00", "14:00"],
      wednesday: [""],
      thursday: ["12:00", "14:00"],
      friday: [""],
      group: "4NM40",
      profesor: "RUTH BLAS VAZQUEZ",
      asignatura: "ADMINISTRACIÓN DE BASES DE DATOS",
    },
    {
      idschedule: 190,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 27,
      teacher_idTeacher: 143,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM40",
      profesor: "VICTOR L. SANDOVAL GONZALEZ",
      asignatura: "SEGURIDAD INFORMÁTICA",
    },
    {
      idschedule: 247,
      shift: "M",
      group_idgroup: 101,
      course_idCourse: 36,
      teacher_idTeacher: 174,
      building: "CS",
      classroom: 0,
      monday: [""],
      tuesday: ["11:00", "13:00"],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "5NM50",
      profesor: "YOLANDA GUADARRAMA ALBA",
      asignatura: "APLICACIÓN DE LA CIENCIA ECONÓMICA",
    },
  ],
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 147,
      shift: "M",
      group_idgroup: 45,
      course_idCourse: 24,
      teacher_idTeacher: 109,
      building: "LE",
      classroom: 1,
      monday: ["08:30", "10:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: [""],
      group: "3NM42",
      profesor: "ARMANDO TORRES CORONEL",
      asignatura: "DISPOSITIVOS PROGRAMABLES",
    },
    {
      idschedule: 185,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 26,
      teacher_idTeacher: 141,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["12:00", "14:00"],
      wednesday: [""],
      thursday: ["12:00", "14:00"],
      friday: [""],
      group: "4NM40",
      profesor: "RUTH BLAS VAZQUEZ",
      asignatura: "ADMINISTRACIÓN DE BASES DE DATOS",
    },
    {
      idschedule: 190,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 27,
      teacher_idTeacher: 143,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM40",
      profesor: "VICTOR L. SANDOVAL GONZALEZ",
      asignatura: "SEGURIDAD INFORMÁTICA",
    },
    {
      idschedule: 261,
      shift: "M",
      group_idgroup: 103,
      course_idCourse: 36,
      teacher_idTeacher: 181,
      building: "CS",
      classroom: 0,
      monday: [""],
      tuesday: ["11:00", "13:00"],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "5NM52",
      profesor: "JOSE LUIS MELGOZA MARAVILLA",
      asignatura: "APLICACIÓN DE LA CIENCIA ECONÓMICA",
    },
  ],
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 147,
      shift: "M",
      group_idgroup: 45,
      course_idCourse: 24,
      teacher_idTeacher: 109,
      building: "LE",
      classroom: 1,
      monday: ["08:30", "10:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: [""],
      group: "3NM42",
      profesor: "ARMANDO TORRES CORONEL",
      asignatura: "DISPOSITIVOS PROGRAMABLES",
    },
    {
      idschedule: 185,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 26,
      teacher_idTeacher: 141,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["12:00", "14:00"],
      wednesday: [""],
      thursday: ["12:00", "14:00"],
      friday: [""],
      group: "4NM40",
      profesor: "RUTH BLAS VAZQUEZ",
      asignatura: "ADMINISTRACIÓN DE BASES DE DATOS",
    },
    {
      idschedule: 190,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 27,
      teacher_idTeacher: 143,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM40",
      profesor: "VICTOR L. SANDOVAL GONZALEZ",
      asignatura: "SEGURIDAD INFORMÁTICA",
    },
    {
      idschedule: 252,
      shift: "M",
      group_idgroup: 101,
      course_idCourse: 37,
      teacher_idTeacher: 60,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: ["11:00", "13:00"],
      friday: [""],
      group: "5NM50",
      profesor: "JOSE LUIS X RODRIGUEZ",
      asignatura: "TEORÍA DE LA COMPUTACIÓN Y COMPILADORES",
    },
  ],
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 147,
      shift: "M",
      group_idgroup: 45,
      course_idCourse: 24,
      teacher_idTeacher: 109,
      building: "LE",
      classroom: 1,
      monday: ["08:30", "10:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: [""],
      group: "3NM42",
      profesor: "ARMANDO TORRES CORONEL",
      asignatura: "DISPOSITIVOS PROGRAMABLES",
    },
    {
      idschedule: 185,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 26,
      teacher_idTeacher: 141,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["12:00", "14:00"],
      wednesday: [""],
      thursday: ["12:00", "14:00"],
      friday: [""],
      group: "4NM40",
      profesor: "RUTH BLAS VAZQUEZ",
      asignatura: "ADMINISTRACIÓN DE BASES DE DATOS",
    },
    {
      idschedule: 190,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 27,
      teacher_idTeacher: 143,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM40",
      profesor: "VICTOR L. SANDOVAL GONZALEZ",
      asignatura: "SEGURIDAD INFORMÁTICA",
    },
    {
      idschedule: 255,
      shift: "M",
      group_idgroup: 102,
      course_idCourse: 38,
      teacher_idTeacher: 113,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["11:00", "13:00"],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "5NM51",
      profesor: "MARIA CRISTINA GUZMAN CORDERO",
      asignatura: "COMUNICACIÓN DE DATOS",
    },
  ],
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 147,
      shift: "M",
      group_idgroup: 45,
      course_idCourse: 24,
      teacher_idTeacher: 109,
      building: "LE",
      classroom: 1,
      monday: ["08:30", "10:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: [""],
      group: "3NM42",
      profesor: "ARMANDO TORRES CORONEL",
      asignatura: "DISPOSITIVOS PROGRAMABLES",
    },
    {
      idschedule: 185,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 26,
      teacher_idTeacher: 141,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["12:00", "14:00"],
      wednesday: [""],
      thursday: ["12:00", "14:00"],
      friday: [""],
      group: "4NM40",
      profesor: "RUTH BLAS VAZQUEZ",
      asignatura: "ADMINISTRACIÓN DE BASES DE DATOS",
    },
    {
      idschedule: 190,
      shift: "M",
      group_idgroup: 67,
      course_idCourse: 27,
      teacher_idTeacher: 143,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM40",
      profesor: "VICTOR L. SANDOVAL GONZALEZ",
      asignatura: "SEGURIDAD INFORMÁTICA",
    },
    {
      idschedule: 258,
      shift: "M",
      group_idgroup: 102,
      course_idCourse: 39,
      teacher_idTeacher: 151,
      building: "CI",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: ["11:00", "13:00"],
      friday: [""],
      group: "5NM51",
      profesor: "ILIANA LOPEZ VALERIANO",
      asignatura: "PROGRAMACIÓN WEB",
    },
  ],
];
