export const horarios = [
  [
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
    {
      idschedule: 130,
      shift: "M",
      group_idgroup: 41,
      course_idCourse: 19,
      teacher_idTeacher: 97,
      building: "CI",
      classroom: 0,
      monday: [""],
      tuesday: ["13:00", "14:00"],
      wednesday: [""],
      thursday: ["13:00", "15:00"],
      friday: [""],
      group: "3NM30",
      profesor: "LAURA ANGELICA GOMEZ ARAGON",
      asignatura: "DISEÑO DE INTERFACES DE USUARIO",
    },
    {
      idschedule: 195,
      shift: "M",
      group_idgroup: 68,
      course_idCourse: 23,
      teacher_idTeacher: 99,
      building: "CB",
      classroom: 0,
      monday: ["11:00", "13:00"],
      tuesday: [""],
      wednesday: [""],
      thursday: [""],
      friday: ["11:00", "13:00"],
      group: "4NM41",
      profesor: "ERIC PEREZ ALTAMIRANO",
      asignatura: "ESTADÍSTICA",
    },
  ],
];
